package com.view.ui.modules.content.organization


const val EVENT_LIST_SCREEN: String = "EVENT_LIST_SCREEN"
const val EVENT_ORGANIZATION_LIST_SCREEN: String = "EVENT_ORGANIZATION_LIST_SCREEN"
const val EVENT_ORGANIZATION_DETAILS_SCREEN: String = "EVENT_ORGANIZATION_DETAILS_SCREEN"
const val EVENT_DETAILS_SCREEN = "EVENT_DETAILS_SCREEN"
const val EVENT_LIST_WITH_SAVED_CREDENTIALS_SCREEN = "EVENT_LIST_WITH_SAVED_CREDENTIALS_SCREEN"
