package com

const val ACTIVITY_ACTION_DATA_KEY = "ACTIVITY_ACTION_DATA_KEY"
const val FRAGMENT_DATA_KEY = "FRAGMENT_DATA_KEY"
const val DEFAULT_INPUT_DEBOUNCE: Long = 700

//Toolbar
const val BACK_CONTENT_DESCRIPTOR = "BACK_CONTENT_DESCRIPTOR"