package com.view.ui.modules.content

const val EVENT_LIST_SCREEN= "EVENT_LIST_SCREEN"
const val EVENT_LIST_WITH_SAVED_CREDENTIALS_SCREEN = "EVENT_LIST_WITH_SAVED_CREDENTIALS_SCREEN"
const val EVENT_DETAILS_SCREEN = "EVENT_DETAILS_SCREEN"
